language:
  node_js
node_js:
  - "7"
branches:
  only:
    - master
before_script:
  - cd web
  - npm install -g firebase-tools
script:
  - firebase deploy --token $FIREBASE_TOKEN --project metricality-f7392